server:
  port: 9090

spring:
  profiles:
    active: production
  application:
    name: packsendme-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/packsendme/microservice-config
          searchPaths: Configuration